### ISSUE TITLE
Scrolling hit-area is broken with two panes

### ISSUE THREAD

**Issue by Timmmm** [atom/atom-light-ui#37] opened 2016-11-01 11:20 UTC
To reproduce:

1. Open a long document that you can scroll through.
2. Right click->Split right
3. Click on the *top* of the scrollbar handle in the left pane.
4. Try to drag. It jumps a little but then the handle loses focus.

If you try dragging from the bottom of the handle it works. The entire handle in the right pane also works. And with another theme (One Dark) the entire handle works in both panes (though that theme has other issues).

**Comment by Ben3eeE** [comment] 2016-11-01 11:25
What version of Atom and what OS are you using?

**Comment by Timmmm** [comment] 2016-11-01 11:38
Windows 7, Atom 1.11.2.

**Comment by Ben3eeE** [comment] 2016-11-01 11:41
Then this sounds like a duplicate of https://github.com/atom/atom/issues/11484 and will be fixed in Atom 1.12.

**Closed by Ben3eeE** 2016-11-01 11:41 UTC
Labels: more-information-needed
